/**
 * 案件データ定義
 * status: 'active'（進行中）| 'done'（完了）
 * tags: フィルター用タグ配列
 *   'no-hire'        採用者なし
 *   'need-report'    要近況報告
 *   'accepting'      仕事を受け付ける
 *   'contracted'     契約中
 *   'need-inspection'要検収
 *   'unread-msg'     メッセージ未読
 */
const PROJECTS = [
  {
    id: 'GK-2024-001',
    status: 'active',
    tags: ['no-hire'],
    dateRange: '2024/01/15 〜 2024/03/31',
    recruiting: true,
    title: '【東京都渋谷区】スーパーのチラシ配布スタッフ大募集！時給1,200円・週2日〜OK',
    location: '東京都渋谷区',
    wage: '¥1,200〜¥1,500 / 時間',
    contracts: 0,
    inspected: 0,
    needInspection: 0,
    reporting: 0,
    alert: { type: 'red', label: '採用者RL0件' },
    actions: ['applicants', 'procedure'],
  },
  {
    id: 'GK-2024-002',
    status: 'active',
    tags: ['contracted'],
    dateRange: '2024/02/01 〜 2024/04/30',
    recruiting: false,
    title: '【神奈川県横浜市】カフェのホールスタッフ募集　未経験歓迎・シフト自由',
    location: '神奈川県横浜市',
    wage: '¥950〜¥1,100 / 時間',
    contracts: 4,
    inspected: 2,
    needInspection: 1,
    reporting: 1,
    alert: null,
    actions: ['applicants', 'procedure', 'renew'],
  },
  {
    id: 'GK-2024-003',
    status: 'active',
    tags: ['need-report', 'need-inspection'],
    dateRange: '2024/01/01 〜 2024/02/29',
    recruiting: true,
    title: '【埼玉県さいたま市】引越し作業補助スタッフ　土日のみ可・日払いあり',
    location: '埼玉県さいたま市',
    wage: '¥10,000〜¥15,000 / 日',
    contracts: 2,
    inspected: 0,
    needInspection: 2,
    reporting: 0,
    alert: { type: 'orange', label: '要近況報告' },
    actions: ['applicants', 'procedure'],
  },
  {
    id: 'GK-2024-004',
    status: 'active',
    tags: ['contracted', 'accepting'],
    dateRange: '2024/03/01 〜 2024/05/31',
    recruiting: true,
    title: '【千葉県千葉市】大型ショッピングモール内の清掃スタッフ　週3日〜・交通費支給',
    location: '千葉県千葉市',
    wage: '¥1,050 / 時間',
    contracts: 6,
    inspected: 5,
    needInspection: 0,
    reporting: 1,
    alert: null,
    actions: ['applicants', 'procedure', 'renew'],
  },
  {
    id: 'GK-2024-005',
    status: 'active',
    tags: ['unread-msg', 'contracted'],
    dateRange: '2024/02/15 〜 2024/06/30',
    recruiting: false,
    title: '【東京都港区】イベント会場の設営・撤去スタッフ　高時給・交通費全額支給',
    location: '東京都港区',
    wage: '¥1,500〜¥2,000 / 時間',
    contracts: 3,
    inspected: 1,
    needInspection: 1,
    reporting: 1,
    alert: { type: 'red', label: 'メッセージ未読 1件' },
    actions: ['applicants', 'procedure'],
  },
  {
    id: 'GK-2024-006',
    status: 'active',
    tags: ['accepting', 'no-hire'],
    dateRange: '2024/04/01 〜 2024/07/31',
    recruiting: true,
    title: '【東京都新宿区】飲食店のキッチンスタッフ　週2〜OK・まかない付き',
    location: '東京都新宿区',
    wage: '¥1,100〜¥1,300 / 時間',
    contracts: 0,
    inspected: 0,
    needInspection: 0,
    reporting: 0,
    alert: { type: 'red', label: '採用者RL0件' },
    actions: ['applicants', 'procedure'],
  },
  {
    id: 'GK-2024-007',
    status: 'active',
    tags: ['need-inspection'],
    dateRange: '2024/03/15 〜 2024/06/15',
    recruiting: false,
    title: '【大阪府大阪市】倉庫内ピッキング作業スタッフ　夜勤あり・高時給',
    location: '大阪府大阪市',
    wage: '¥1,200〜¥1,600 / 時間',
    contracts: 5,
    inspected: 3,
    needInspection: 2,
    reporting: 0,
    alert: null,
    actions: ['applicants', 'procedure'],
  },
  {
    id: 'GK-2024-008',
    status: 'done',
    tags: [],
    dateRange: '2023/10/01 〜 2023/12/31',
    recruiting: false,
    title: '【福岡県福岡市】コールセンタースタッフ　在宅勤務可・研修充実',
    location: '福岡県福岡市',
    wage: '¥1,000〜¥1,200 / 時間',
    contracts: 8,
    inspected: 8,
    needInspection: 0,
    reporting: 0,
    alert: null,
    actions: ['applicants', 'procedure'],
  },
  {
    id: 'GK-2024-009',
    status: 'done',
    tags: [],
    dateRange: '2023/11/01 〜 2024/01/31',
    recruiting: false,
    title: '【愛知県名古屋市】年末年始の配送ドライバー補助　普通免許あればOK',
    location: '愛知県名古屋市',
    wage: '¥1,300 / 時間',
    contracts: 3,
    inspected: 3,
    needInspection: 0,
    reporting: 0,
    alert: null,
    actions: ['applicants', 'procedure'],
  },
];
